import 'package:analytics_sdk/manager/page_name_manager.dart';
import 'package:analytics_sdk/observer/page_lifecycle_observer.dart';

void initPage() {
  PageNameMapper.addMappings({
    'main': {'key': 'main', 'name': '主页面'},
    '': {'key': 'launch', 'name': '启动页'},
    'launch': {'key': 'launch', 'name': '启动页'},
    'home': {'key': 'home', 'name': '首页'},
    'anWang': {'key': 'anWang', 'name': '暗网页'},
    'vlog': {'key': 'vlog', 'name': '短视频页'},
    'ych': {'key': 'ych', 'name': '原创社区页'},
    'community': {'key': 'community', 'name': '社区页'},
    'mine': {'key': 'mine', 'name': '我的'},
    'vlogSecond': {'key': 'vlogSecond', 'name': '短视频二级页'},
    'vlogTag/:tag': {'key': 'vlogTag', 'name': '短视频标签页'},
    'soulGroupChatList': {'key': 'soulGroupChatList', 'name': '群聊列表页'},
    'soulGroupChatTopMsg': {'key': 'soulGroupChatTopMsg', 'name': '群聊置顶消息页'},
    'soulGroupDetailChatList': {
      'key': 'soulGroupDetailChatList',
      'name': '群聊详情页'
    },
    'soulGroupMembersList': {'key': 'soulGroupMembersList', 'name': '群成员页'},
    'cartoon': {'key': 'cartoon', 'name': '动漫视频页'},
    'cartoonMore/:sort/:title': {'key': 'cartoonMore', 'name': '更多动漫页'},
    'cartoonDetail': {'key': 'cartoonDetail', 'name': '动漫详情页'},
    'game': {'key': 'game', 'name': '游戏页'},
    'gameMore/:sort/:title': {'key': 'gameMore', 'name': '更多游戏页'},
    'gameNav/:type/:title': {'key': 'gameNav', 'name': '游戏导航页'},
    'gameDetail': {'key': 'gameDetail', 'name': '游戏详情页'},
    'gameTag/:tag': {'key': 'gameTag', 'name': '游戏标签页'},
    'ktloadwebview/:url': {'key': 'webview', 'name': '网页视图页'},
    'bitPostDetail/:id': {'key': 'bitPostDetail', 'name': '种子帖子详情页'},
    'mineVipCenter': {'key': 'mineVipCenter', 'name': 'VIP中心页'},
    'mineVipUpgrade': {'key': 'mineVipUpgrade', 'name': 'VIP升级页'},
    'mineCoinRecharge': {'key': 'mineCoinRecharge', 'name': '金币充值页'},
    'mineCoinDetail': {'key': 'mineCoinDetail', 'name': '金币明细页'},
    'rankList': {'key': 'rankList', 'name': '排行榜页'},
    'mineRechargeRecord/:type': {'key': 'mineRechargeRecord', 'name': '充值记录页'},
    'communityIssue/:type/:org': {'key': 'communityIssue', 'name': '发布帖子页'},
    'communityModule': {'key': 'communityModule', 'name': '社区模块页'},
    'communityTieztDetail/:id': {
      'key': 'communityTieztDetail',
      'name': '社区帖子详情页'
    },
    'login': {'key': 'login', 'name': '登录页'},
    'mineSetup': {'key': 'mineSetup', 'name': '设置页'},
    'mineShareToUser': {'key': 'mineShareToUser', 'name': '分享给用户页'},
    'mineShareToUserRecord': {'key': 'mineShareToUserRecord', 'name': '分享记录页'},
    'mineAgent': {'key': 'mineAgent', 'name': '代理页'},
    'mineAgentProfit': {'key': 'mineAgentProfit', 'name': '代理收益页'},
    'mineAgentPromoteData': {'key': 'mineAgentPromoteData', 'name': '代理推广数据页'},
    'customerService': {'key': 'customerService', 'name': '客服网页'},
    'mineWithdrawal/:isAgent': {'key': 'mineWithdrawal', 'name': '提现页'},
    'mineWithdrawalRecord': {'key': 'mineWithdrawalRecord', 'name': '提现记录页'},
    'mineWithdrawalBankList': {'key': 'mineWithdrawalBankList', 'name': '提现银行卡列表页'},
    'mineWelfare/:index': {'key': 'mineWelfare', 'name': '福利页'},
    'aiServer': {'key': 'aiServer', 'name': 'AI服务页'},
    'aiMagic': {'key': 'aiMagic', 'name': 'AI魔法页'},
    'aiArt': {'key': 'aiArt', 'name': 'AI美术页'},
    'aiNovel': {'key': 'aiNovel', 'name': 'AI小说页'},
    'aiAudio': {'key': 'aiAudio', 'name': 'AI语音页'},
    'aiNovelDetail': {'key': 'aiNovelDetail', 'name': 'AI小说详情页'},
    'aiFaceSwap': {'key': 'aiFaceSwap', 'name': 'AI换脸页'},
    'aiVideoFaceSwap': {'key': 'aiVideoFaceSwap', 'name': 'AI视频换脸页'},
    'aiOffDeRobe': {'key': 'aiOffDeRobe', 'name': 'AI脱衣页'},
    'aiKiss': {'key': 'aiKiss', 'name': 'AI接吻页'},
    'minePost': {'key': 'minePost', 'name': '我的帖子页'},
    'mineIncomeDetail': {'key': 'mineIncomeDetail', 'name': '收入明细页'},
    'mineCollection': {'key': 'mineCollection', 'name': '我的收藏页'},
    'userCenter/:aff': {'key': 'userCenter', 'name': '用户中心页'},
    'chatMessage/:toUuid/:nickName/:thumb': {
      'key': 'chatMessage',
      'name': '聊天消息页'
    },
    'mineFollowing': {'key': 'mineFollowing', 'name': '我的关注页'},
    'originalEnter': {'key': 'originalEnter', 'name': '原创入口页'},
    'communityTagDetail/:id': {'key': 'communityTagDetail', 'name': '社区标签详情页'},
    'mineBuy': {'key': 'mineBuy', 'name': '购买页'},
    'minAIRecord': {'key': 'minAIRecord', 'name': 'AI生成记录页'},
    'videoDetail': {'key': 'videoDetail', 'name': '视频详情页'},
    'voicePlayerContent': {'key': 'voicePlayerContent', 'name': '语音播放器内容页'},
    'livesDetail': {'key': 'livesDetail', 'name': '直播视频详情页'},
    'mineDownload':  {'key': 'mineDownload', 'name': '我的下载页'},
    'mineFillCode/:title': {'key': 'mineFillCode', 'name': '填写邀请码页'},
    'mine_bind_email': {'key': 'mine_bind_email', 'name': '绑定邮箱页'},
    'mineHelp': {'key': 'mineHelp', 'name': '帮助页'},
    'mineOfficialGroup': {'key': 'mineOfficialGroup', 'name': '官方群页'},
    'search': {'key': 'search', 'name': '搜索页'},
    'searchResult/:title': {'key': 'searchResult', 'name': '搜索结果页'},
    'moreVideo/:name/:id': {'key': 'moreVideo', 'name': '更多视频页'},
    'mineMessageCenter': {'key': 'mineMessageCenter', 'name': '消息中心页'},
    'mineSystemMessage': {'key': 'mineSystemMessage', 'name': '系统消息页'},
    'mediaViewer': {'key': 'mediaViewer', 'name': '媒体查看页'},
    'localVideo': {'key': 'localVideo', 'name': '本地视频页'},
    'localVoice': {'key': 'localVoice', 'name': '本地语音播放页'},
    'aiMagicDetail': {'key': 'aiMagicDetail', 'name': 'AI魔法详情页'},
  });

  PageNameMapper.addMappings({
    'heiLiao': {'key': 'heiLiao', 'name': '黑料页'},
    'heiLiaoDetail': {'key': 'heiLiaoDetail', 'name': '黑料详情页'},
    'heiLiaoTagList': {'key': 'heiLiaoTagList', 'name': '黑料标签列表页'},
    'crack1': {'key': 'crack1', 'name': '破解页'},
    'crackDetail': {'key': 'crackDetail', 'name': '破解详情页'},
    'aw91': {'key': 'aw91', 'name': '91暗网页'},
    'aw91VideoDetail': {'key': 'aw91VideoDetail', 'name': '91暗网视频详情'},
    'aw91VideoTag': {'key': 'aw91VideoTag', 'name': '91暗网标签页'},
    'aw91VideoSearch': {'key': 'aw91VideoSearch', 'name': '91暗网搜索页'},
    'aw91VideoSearchResult': {'key': 'aw91VideoSearchResult', 'name': '91暗网搜索结果页'},
    'hjsqApp': {'key': 'hjsqApp', 'name': '海角社区页'},
    'hjsqVideoDetail': {'key': 'hjsqVideoDetail', 'name': '海角视频详情'},
    'hjsqVideoTag': {'key': 'hjsqVideoTag', 'name': '海角标签页'},
    'hjsqVideoSearch': {'key': 'hjsqVideoSearch', 'name': '海角搜索页'},
    'hjsqVideoSearchResult': {'key': 'hjsqVideoSearchResult', 'name': '海角搜索结果页'},
    'tiktok51App': {'key': 'tiktok51App', 'name': '51Tiktok页'},
    'tiktok51VideoDetail': {'key': 'tiktok51VideoDetail', 'name': '51Tiktok视频详情'},
    'tiktok51VideoTag': {'key': 'tiktok51VideoTag', 'name': '51Tiktok标签页'},
    'tiktok51VideoSearch': {'key': 'tiktok51VideoSearch', 'name': '51Tiktok搜索页'},
    'tiktok51VideoSearchResult': {'key': 'tiktok51VideoSearchResult', 'name': '51Tiktok搜索结果页'},
    'tiktok51Topic': {'key': 'tiktok51Topic', 'name': '51Tiktok话题页'},
    'tiktok51More': {'key': 'tiktok51More', 'name': '51Tiktok更多页'},
    'pzhanVideoDetail': {'key': 'pzhanVideoDetail', 'name': 'P站视频详情'},
    'pzhanVideoTag': {'key': 'pzhanVideoTag', 'name': 'P站标签页'},
    'pzhanVideoSearch': {'key': 'pzhanVideoSearch', 'name': 'P站搜索页'},
    'pzhanVideoSearchResult': {'key': 'pzhanVideoSearchResult', 'name': 'P站搜索结果页'},
    'pzhanTopic': {'key': 'pzhanTopic', 'name': 'P站话题页'},
    'pzhanMore': {'key': 'pzhanMore', 'name': 'P站更多页'},
    'caoliu': {'key': 'caoliu', 'name': '草榴页'},
    'clVideoDetail': {'key': 'clVideoDetail', 'name': '草榴视频详情'},
    'clVideoTag': {'key': 'clVideoTag', 'name': '草榴标签页'},
    'clVideoSearch': {'key': 'clVideoSearch', 'name': '草榴搜索页'},
    'clVideoSearchResult': {'key': 'clVideoSearchResult', 'name': '草榴搜索结果页'},
    'zpcApp': {'key': 'zpcApp', 'name': '制片厂页'},
    'zpcVideoDetail': {'key': 'zpcVideoDetail', 'name': '制片厂视频详情'},
    'zpcVideoTag': {'key': 'zpcVideoTag', 'name': '制片厂标签页'},
    'zpcVideoSearch': {'key': 'zpcVideoSearch', 'name': '制片厂搜索页'},
    'zpcVideoSearchResult': {'key': 'zpcVideoSearchResult', 'name': '制片厂搜索结果页'},
    'asmr': {'key': 'asmr', 'name': 'ASMR页'},
    'torrentDownload': {'key': 'torrentDownload', 'name': '种子下载页'},
    'mineBrowseRecord': {'key': 'mineBrowseRecord', 'name': '浏览记录页'},
    'mineShareInvite': {'key': 'mineShareInvite', 'name': '分享邀请页'},
    'mineFansFollow': {'key': 'mineFansFollow', 'name': '粉丝关注页'},
    'tiktokSearchResult/:kwy': {'key': 'tiktokSearchResult', 'name': 'Tiktok搜索结果页'},
    'tiktokCreator': {'key': 'tiktokCreator', 'name': 'Tiktok创作达人页'},
    'tiktokUserWorks/:id/:userName': {'key': 'tiktokUserWorks', 'name': 'Tiktok用户作品页'},
    'tiktokDiscover': {'key': 'tiktokDiscover', 'name': 'Tiktok发现页'},
    'tiktokCategoryOrTagDetail/:id/:type/:has_sort/:title': {
      'key': 'tiktokCategoryOrTagDetail',
      'name': 'Tiktok分类标签详情页'
    },
    'tiktokVideoDetail/:id': {'key': 'tiktokVideoDetail', 'name': 'Tiktok视频详情页'},
    'tiktokSearch': {'key': 'tiktokSearch', 'name': 'Tiktok搜索页'},
    'tiktokDaily': {'key': 'tiktokDaily', 'name': 'Tiktok每日推荐页'},
    'xiaolanSearchResult/:kwy': {'key': 'xiaolanSearchResult', 'name': '小蓝搜索结果页'},
    'xiaolanCreator': {'key': 'xiaolanCreator', 'name': '小蓝创作达人页'},
    'xiaolanUserWorks/:id/:userName': {'key': 'xiaolanUserWorks', 'name': '小蓝用户作品页'},
    'xiaolanDiscover': {'key': 'xiaolanDiscover', 'name': '小蓝发现页'},
    'xiaolanCategoryOrTagDetail/:id/:type/:has_sort/:title': {
      'key': 'xiaolanCategoryOrTagDetail',
      'name': '小蓝分类标签详情页'
    },
    'xiaolanVideoDetail/:id': {'key': 'xiaolanVideoDetail', 'name': '小蓝视频详情页'},
    'xiaolanSearch': {'key': 'xiaolanSearch', 'name': '小蓝搜索页'},
    'xiaolanDaily': {'key': 'xiaolanDaily', 'name': '小蓝每日推荐页'},
  });

  // 在首个路由生命周期触发前，先设置一个可用的默认页面，
  // 避免埋点读取 currentPageKey / pageName 为空。
  final defaultPageKey = PageNameMapper.resolvePageInfo('launch').key;
  PageLifecycleObserver.recordNavigation(defaultPageKey);
}
